import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

import { LayersIcon, MagnifyingGlassIcon } from '@radix-ui/react-icons'
import Sidebar from '@/components/sidebar'

import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { redirect } from 'next/navigation'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	async function search(formData: FormData) {
		'use server'
		redirect(`/search?q=${formData.get('q')}`)
	}

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header className="p-4 border-b flex justify-between">
					<h1 className="text-xl font-bold flex items-center gap-2">
						<LayersIcon width={24} height={24} />
						Next App
					</h1>

					<form className="flex gap-1" action={search}>
						<Input placeholder="Search Movie" name="q" />
						<Button type="submit">
							<MagnifyingGlassIcon />
						</Button>
					</form>
				</header>

				<div className="flex p-4">
					<Sidebar />
					<main className="pl-4 flex-grow">{children}</main>
				</div>
			</body>
		</html>
	)
}
